package de.htwg.se.dominion.model

import org.scalatest._

class CardsSpec extends WordSpec with Matchers {
  "A Card" when {
    "new" should {
      val copper = new Cards (0, 1, 0, 0, 0, 0, 0, "None", "Copper","Money")
      val gold = new Cards (6, 3, 0, 0, 0, 0, 0, "None", "Gold", "Money")
      val silver = new Cards (3, 2, 0, 0, 0, 0, 0, "None", "Silver", "Money")
      val mansion = new Cards (2, 0, 1, 0, 0, 0, 0, "None", "Mansion", "Money")
      val duchy = new Cards (5, 0, 3, 0, 0, 0, 0, "None", "Duchy", "Money")
      val province = new Cards (8, 0, 6, 0, 0, 0, 0, "None", "Province", "Money")
      val village = new Cards(3,0,0,2,0,0,1,"None","Village", "Action")
      val festival = new Cards(5,0,0,2,1,2,0,"None","Festival", "Action")
      val cellar = new Cards(2,0,0,1,0,0,0,"Discard any number of cards, then draw that many", "Cellar", "Action")
      val mine = new Cards(5,0,0,0,0,0,0,"You may trash a Treasure from your hand. Gain a Treasure to your hand costing up to 3 more than it.","Mine", "Action")
      val smithy = new Cards(4,0,0,0,0,0,3,"None","Smithy", "Action")
      val remodel = new Cards(4,0,0,0,0,0,0,"Trash a card from your hand. Gain a card costing up to 2 more than it.","Remodel", "Action")
      val merchant = new Cards(3,0,0,1,0,0,1,"The first time you play a Silver this turn, +1", "Merchant", "Action")
      val workshop = new Cards(3,0,0,0,0,0,0,"Gain a card costing up to 4.", "Workshop", "Action")
      val gardens = new Cards(4,0,0,0,0,0,0,"Worth 1 WinningPonit per 10 cards you have(round down)","Gardens", "Action")
      val market = new Cards(5,0,0,1,1,1,1,"None","Market", "Action")
      "have a BuyValue" in {
        copper.CostValue should be(0)
        silver.CostValue should be(3)
        gold.CostValue should be(6)
        mansion.CostValue should be(2)
        duchy.CostValue should be(5)
        province.CostValue should be(8)
        village.CostValue should be(3)
        festival.CostValue should be(5)
        cellar.CostValue should be(2)
        mine.CostValue should be(5)
        smithy.CostValue should be(4)
        remodel.CostValue should be(4)
        merchant.CostValue should be(3)
        workshop.CostValue should be(3)
        gardens.CostValue should be(4)
        market.CostValue should be(5)
      }
      "have a MoneyValue" in {
        copper.MoneyValue should be(1)
        silver.MoneyValue should be(2)
        gold.MoneyValue should be(3)
        mansion.MoneyValue should be(0)
        duchy.MoneyValue should be(0)
        province.MoneyValue should be(0)
        village.MoneyValue should be(0)
        festival.MoneyValue should be(0)
        cellar.MoneyValue should be(0)
        mine.MoneyValue should be(0)
        smithy.MoneyValue should be(0)
        remodel.MoneyValue should be(0)
        merchant.MoneyValue should be(0)
        workshop.MoneyValue should be(0)
        gardens.MoneyValue should be(0)
        market.MoneyValue should be(0)
      }
      "have a WpValue" in {
        copper.WpValue should be(0)
        silver.WpValue should be(0)
        gold.WpValue should be(0)
        mansion.WpValue should be(1)
        duchy.WpValue should be(3)
        province.WpValue should be(6)
        village.WpValue should be(0)
        festival.WpValue should be(0)
        cellar.WpValue should be(0)
        mine.WpValue should be(0)
        smithy.WpValue should be(0)
        remodel.WpValue should be(0)
        merchant.WpValue should be(0)
        workshop.WpValue should be(0)
        gardens.WpValue should be(0)
        market.WpValue should be(0)
      }
      "have a ActionValue" in {
        copper.ActionValue should be(0)
        silver.ActionValue should be(0)
        gold.ActionValue should be(0)
        mansion.ActionValue should be(0)
        duchy.ActionValue should be(0)
        province.ActionValue should be(0)
        village.ActionValue should be(2)
        festival.ActionValue should be(2)
        cellar.ActionValue should be(1)
        mine.ActionValue should be(0)
        smithy.ActionValue should be(0)
        remodel.ActionValue should be(0)
        merchant.ActionValue should be(1)
        workshop.ActionValue should be(0)
        gardens.ActionValue should be(0)
        market.ActionValue should be(1)
      }
      "have a BuyadditionValue" in {
        copper.BuyAdditionValue should be(0)
        silver.BuyAdditionValue should be(0)
        gold.BuyAdditionValue should be(0)
        mansion.BuyAdditionValue should be(0)
        duchy.BuyAdditionValue should be(0)
        province.BuyAdditionValue should be(0)
        village.BuyAdditionValue should be(0)
        festival.BuyAdditionValue should be(1)
        cellar.BuyAdditionValue should be(0)
        mine.BuyAdditionValue should be(0)
        smithy.BuyAdditionValue should be(0)
        remodel.BuyAdditionValue should be(0)
        merchant.BuyAdditionValue should be(0)
        workshop.BuyAdditionValue should be(0)
        gardens.BuyAdditionValue should be(0)
        market.BuyAdditionValue should be(1)
      }
      "have a BonusMoneyValue" in {
        copper.BonusMoneyValue should be(0)
        silver.BonusMoneyValue should be(0)
        gold.BonusMoneyValue should be(0)
        mansion.BonusMoneyValue should be(0)
        duchy.BonusMoneyValue should be(0)
        province.BonusMoneyValue should be(0)
        village.BonusMoneyValue should be(0)
        festival.BonusMoneyValue should be(2)
        cellar.BonusMoneyValue should be(0)
        mine.BonusMoneyValue should be(0)
        smithy.BonusMoneyValue should be(0)
        remodel.BonusMoneyValue should be(0)
        merchant.BonusMoneyValue should be(0)
        workshop.BonusMoneyValue should be(0)
        gardens.BonusMoneyValue should be(0)
        market.BonusMoneyValue should be(1)
      }
      "have a DrawingValue" in {
        copper.DrawingValue should be(0)
        silver.DrawingValue should be(0)
        gold.DrawingValue should be(0)
        mansion.DrawingValue should be(0)
        duchy.DrawingValue should be(0)
        province.DrawingValue should be(0)
        village.DrawingValue should be(1)
        festival.DrawingValue should be(0)
        cellar.DrawingValue should be(0)
        mine.DrawingValue should be(0)
        smithy.DrawingValue should be(3)
        remodel.DrawingValue should be(0)
        merchant.DrawingValue should be(1)
        workshop.DrawingValue should be(0)
        gardens.DrawingValue should be(0)
        market.DrawingValue should be(1)
      }
      "have a EffectValue" in {
        copper.EffectValue should be("None")
        silver.EffectValue should be("None")
        gold.EffectValue should be("None")
        mansion.EffectValue should be("None")
        duchy.EffectValue should be("None")
        province.EffectValue should be("None")
        village.EffectValue should be("None")
        festival.EffectValue should be("None")
        cellar.EffectValue should be("Discard any number of cards, then draw that many")
        mine.EffectValue should be("You may trash a Treasure from your hand. Gain a Treasure to your hand costing up to 3 more than it.")
        smithy.EffectValue should be("None")
        remodel.EffectValue should be("Trash a card from your hand. Gain a card costing up to 2 more than it.")
        merchant.EffectValue should be("The first time you play a Silver this turn, +1")
        workshop.EffectValue should be("Gain a card costing up to 4.")
        gardens.EffectValue should be("Worth 1 WinningPonit per 10 cards you have(round down)")
        market.EffectValue should be("None")
      }
      "have a CardName" in {
        copper.CardName should be("Copper")
        silver.CardName should be("Silver")
        gold.CardName should be("Gold")
        mansion.CardName should be("Mansion")
        duchy.CardName should be("Duchy")
        province.CardName should be("Province")
        village.CardName should be("Village")
        festival.CardName should be("Festival")
        cellar.CardName should be("Cellar")
        mine.CardName should be("Mine")
        smithy.CardName should be("Smithy")
        remodel.CardName should be("Remodel")
        merchant.CardName should be("Merchant")
        workshop.CardName should be("Workshop")
        gardens.CardName should be("Gardens")
        market.CardName should be("Market")
      }
    }
  }
}